from __future__ import annotations

TRADE_EXECUTE_REQUESTED = 'TRADE_EXECUTE_REQUESTED'
TRADE_EXECUTION_REJECTED = 'TRADE_EXECUTION_REJECTED'
TRADE_EXECUTED = 'TRADE_EXECUTED'
TRADE_EXITED = 'TRADE_EXITED'

__all__ = [
    'TRADE_EXECUTE_REQUESTED',
    'TRADE_EXECUTION_REJECTED',
    'TRADE_EXECUTED',
    'TRADE_EXITED',
]
