apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krsh-ingress
  namespace: krsh
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: krsh.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: krsh-service
                port:
                  number: 80
