version: "3.9"

services:
  vinayak-api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    image: vinayak-api:latest
    container_name: vinayak_api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: "local"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
    volumes:
      - ../../app/vinayak/data:/app/app/vinayak/data
    restart: unless-stopped
