apiVersion: v1
kind: ConfigMap
metadata:
  name: vinayak-config
  namespace: vinayak
data:
  VINAYAK_API_BASE_URL: "http://vinayak-api:8000"
  VINAYAK_REDIS_URL: "redis://vinayak-redis:6379/0"
  VINAYAK_LOG_LEVEL: "INFO"
