EVENT_SIGNAL_GENERATED = 'signal.generated'
EVENT_REVIEWED_TRADE_CREATED = 'trade.reviewed'
EVENT_REVIEWED_TRADE_STATUS_UPDATED = 'reviewed_trade.status.updated'
EVENT_TRADE_EXECUTE_REQUESTED = 'trade.execute.requested'
EVENT_TRADE_EXECUTED = 'trade.executed'
EVENT_NOTIFICATION_REQUESTED = 'notification.requested'
EVENT_ANALYSIS_COMPLETED = 'analysis.completed'

# Backward-compatible aliases for older imports and outbox consumers.
EVENT_TRADE_REVIEWED = EVENT_REVIEWED_TRADE_CREATED

__all__ = [
    'EVENT_SIGNAL_GENERATED',
    'EVENT_REVIEWED_TRADE_CREATED',
    'EVENT_REVIEWED_TRADE_STATUS_UPDATED',
    'EVENT_TRADE_REVIEWED',
    'EVENT_TRADE_EXECUTE_REQUESTED',
    'EVENT_TRADE_EXECUTED',
    'EVENT_NOTIFICATION_REQUESTED',
    'EVENT_ANALYSIS_COMPLETED',
]

