apiVersion: v1
kind: ConfigMap
metadata:
  name: krsh-config
  namespace: krsh
data:
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  EXECUTION_MODE: "PAPER"
  AWS_DEFAULT_REGION: "ap-south-1"
