FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY app /app/app
COPY vinayak /app/vinayak

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "app/vinayak/ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
